protected/models/Kegiatan.php
<?php

/**
 * This is the model class for table "kegiatan".
 *
 * The followings are the available columns in table 'kegiatan':
 * @property integer $kg_id
 * @property string $nama_kegiatan
 * @property string $tgl_kegiatan
 * @property string $ktg_kegiatan
 * @property string $lokasi_kegiatan
 * @property string $person_in_charge
 * @property string $created
 * @property string $updated
 */
class Kegiatan extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'kegiatan';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama_kegiatan, tgl_kegiatan, ktg_kegiatan, lokasi_kegiatan, person_in_charge, created, updated', 'required'),
			array('nama_kegiatan, lokasi_kegiatan, person_in_charge', 'length', 'max'=>255),
			array('ktg_kegiatan', 'length', 'max'=>100),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('kg_id, nama_kegiatan, tgl_kegiatan, ktg_kegiatan, lokasi_kegiatan, person_in_charge, created, updated', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'kg_id' => 'Kegiatan ID',
			'nama_kegiatan' => 'Nama Kegiatan',
			'tgl_kegiatan' => 'Tanggal Kegiatan',
			'ktg_kegiatan' => 'Keterangan Kegiatan',
			'lokasi_kegiatan' => 'Lokasi Kegiatan',
			'person_in_charge' => 'Person In Charge',
			'created' => 'Created',
			'updated' => 'Updated',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('kg_id',$this->kg_id);
		$criteria->compare('nama_kegiatan',$this->nama_kegiatan,true);
		$criteria->compare('tgl_kegiatan',$this->tgl_kegiatan,true);
		$criteria->compare('ktg_kegiatan',$this->ktg_kegiatan,true);
		$criteria->compare('lokasi_kegiatan',$this->lokasi_kegiatan,true);
		$criteria->compare('person_in_charge',$this->person_in_charge,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('updated',$this->updated,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Kegiatan the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function hari_ini($data){
		$datee = date('d-m-Y',strtotime($data));
		$hari = date ("D",strtotime($data));
	 
		switch($hari){
			case 'Sun':
				$hari_ini = "Minggu";
			break;
	 
			case 'Mon':			
				$hari_ini = "Senin";
			break;
	 
			case 'Tue':
				$hari_ini = "Selasa";
			break;
	 
			case 'Wed':
				$hari_ini = "Rabu";
			break;
	 
			case 'Thu':
				$hari_ini = "Kamis";
			break;
	 
			case 'Fri':
				$hari_ini = "Jumat";
			break;
	 
			case 'Sat':
				$hari_ini = "Sabtu";
			break;
			
			default:
				$hari_ini = "Tidak di ketahui";		
			break;
		}
	 
		return $hari_ini.", ".$datee;
	}	

	public static function getKegiatan(){
		$sql = "SELECT * FROM kegiatan";
		$command = YII::app()->db->createCommand($sql);
		return $command->queryAll();
	}	
}

protected/controllers/KegiatanController.php
<?php

class KegiatanController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','admin','delete','hapus','excel','calendarEvents'),
				'expression'=>'Yii::app()->user->isAdministrator()',
			),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','admin','delete','hapus','excel','calendarEvents'),
				'expression'=>'Yii::app()->user->isAdminbidang()',
			),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','admin','delete','hapus','excel','calendarEvents'),
				'expression'=>'Yii::app()->user->isVisitor()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),			
		);
	}

	public function actionExcel()
	{
		$this->layout = "go";
		$this->render('_excel');
	}

	public function actionCalendarEvents()
	{	 	
	 	$items = array();
	 	$model=Kegiatan::model()->findAll();	
		foreach ($model as $value) {
			$items[]=array(
				'id'=>$value->kg_id,
				'title'=>$value->nama_kegiatan,
				'start'=>$value->tgl_kegiatan,
				'end'=>$value->tgl_kegiatan,
				//'color'=>'#CC0000',
	        	//'allDay'=>true,
	        	//'url'=>'http://anyurl.com'
			);
		}
	    echo CJSON::encode($items);
	    Yii::app()->end();
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		
		if (@$_GET['asModal']==true)
		{
			$this->renderPartial('view',
				array('model'=>$this->loadModel($id)),false,true
			);
		}
		else{
			$this->render('view',array(
				'model'=>$this->loadModel($id),
			));
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Kegiatan;
		$model->created = date('Y-m-d h-m-s');
		$model->updated = '0000-00-00 00-00-00';

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kegiatan']))
		{
			$model->attributes=$_POST['Kegiatan'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$model->updated = date('Y-m-d h-m-s');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kegiatan']))
		{
			$model->attributes=$_POST['Kegiatan'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	public function actionHapus($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Kegiatan');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Kegiatan('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Kegiatan']))
			$model->attributes=$_GET['Kegiatan'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Kegiatan the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Kegiatan::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Kegiatan $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='kegiatan-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/kegiatan/_excel.php
<?php
// Skrip berikut ini adalah skrip yang bertugas untuk meng-export data tadi ke excell
date_default_timezone_set('Asia/Jakarta');

$date = date('Y-m-d H:i:s');

header("Content-type: application/vnd-ms-excel");
header("Content-Disposition: attachment; filename=Data Kalendar Kegiatan - $date.xls");
?>
<h3>Data Kalendar Kegiatan</h3>
<small>Pengunduhan tanggal : <?php echo $date;?></small>
<table border="1" cellpadding="5">
    <th width="10px">No</th>
    <th><center>Nama Kegiatan</center></th>
    <th><center>Tanggal Kegiatan</center></th>
    <th><center>Keterangan Kegiatan</center></th>
    <th><center>Lokasi Kegiatan</center></th>
<?php
    $no = 0; 
    foreach (Kegiatan::getKegiatan() as $data) {   
    $no++;
?>  
    <tr>
        <td><?php echo $no;?></td>
        <td><?php echo $data['nama_kegiatan'];?></td>
        <td><?php echo Kegiatan::model()->hari_ini($data['tgl_kegiatan']);?></td>
        <td><?php echo $data['ktg_kegiatan'];?></td>
        <td><?php echo $data['lokasi_kegiatan'];?></td>
    </tr>
<?php } ?> 
</table>

protected/views/kegiatan/_form.php
<?php
/* @var $this KegiatanController */
/* @var $model Kegiatan */
/* @var $form CActiveForm */
?>

<div class="col-lg-12">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'kegiatan-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>


	<div class="form-group">
		<?php echo $form->labelEx($model,'nama_kegiatan'); ?>
		<?php echo $form->textField($model,'nama_kegiatan',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
		<?php echo $form->error($model,'nama_kegiatan'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'tgl_kegiatan'); ?>
		<?php echo $form->dateField($model,'tgl_kegiatan',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>		
		<?php echo $form->error($model,'tgl_kegiatan'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'ktg_kegiatan'); ?>
		<?php echo $form->dropDownList($model,'ktg_kegiatan', 
								array('Rapat'=>'Rapat',
									'Kordinasi'=>'Kordinasi',
									'Kunjungan'=>'Kunjungan',
									'Kegiatan Intern'=>'Kegiatan Intern',
									'Kegiatan Ekstern'=>'Kegiatan Ekstern',
									'Kegiatan Pelatihan'=>'Kegiatan Pelatihan',
								),array("empty"=>"-- Pilih Kegiatan --",
								'style'=>'width:100;','class' => 'form-control')
							);
		?>	
		<?php echo $form->error($model,'ktg_kegiatan'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'lokasi_kegiatan'); ?>
		<?php echo $form->textField($model,'lokasi_kegiatan',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
		<?php echo $form->error($model,'lokasi_kegiatan'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'person_in_charge'); ?>
		<?php echo $form->textField($model,'person_in_charge',array('size'=>10,'maxlength'=>255,'class' => 'form-control')); ?>
		<?php echo $form->error($model,'person_in_charge'); ?>
	</div>

	<div class="form-group">
     	<?php echo CHtml::submitButton('Save', array('class' => 'btn btn-primary pull-right')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/kegiatan/_search.php
<?php
/* @var $this KegiatanController */
/* @var $model Kegiatan */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'kg_id'); ?>
		<?php echo $form->textField($model,'kg_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nama_kegiatan'); ?>
		<?php echo $form->textField($model,'nama_kegiatan',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tgl_kegiatan'); ?>
		<?php echo $form->textField($model,'tgl_kegiatan'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ktg_kegiatan'); ?>
		<?php echo $form->textField($model,'ktg_kegiatan',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lokasi_kegiatan'); ?>
		<?php echo $form->textField($model,'lokasi_kegiatan',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'person_in_charge'); ?>
		<?php echo $form->textField($model,'person_in_charge',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated'); ?>
		<?php echo $form->textField($model,'updated'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/kegiatan/_view.php
<?php
/* @var $this KegiatanController */
/* @var $data Kegiatan */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('kg_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->kg_id), array('view', 'id'=>$data->kg_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nama_kegiatan')); ?>:</b>
	<?php echo CHtml::encode($data->nama_kegiatan); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tgl_kegiatan')); ?>:</b>
	<?php echo CHtml::encode($data->tgl_kegiatan); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ktg_kegiatan')); ?>:</b>
	<?php echo CHtml::encode($data->ktg_kegiatan); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lokasi_kegiatan')); ?>:</b>
	<?php echo CHtml::encode($data->lokasi_kegiatan); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('person_in_charge')); ?>:</b>
	<?php echo CHtml::encode($data->person_in_charge); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created')); ?>:</b>
	<?php echo CHtml::encode($data->created); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('updated')); ?>:</b>
	<?php echo CHtml::encode($data->updated); ?>
	<br />

	*/ ?>

</div>

protected/views/kegiatan/admin.php
<?php
/* @var $this KegiatanController */
/* @var $model Kegiatan */
$this->pageTitle="Kegiatan";
$this->breadcrumbs=array(
	'Kegiatan'=>array('admin')
);
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#kegiatan-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
            	<div class="pull-right">
				<?php 
				echo CHtml::link('<i class="fa fa-plus"></i> Create',
				array('create'),
				array('class' => 'btn btn-primary','title'=>'Tambah Data Baru'));
				?>
				<?php 
				echo CHtml::link('<i class="fa fa-file-excel-o"></i>',
				array('excel'),
				array('class' => 'btn btn-success','title'=>'Export Ke Excel'));
				?>
				</div>
	            <h6>Data Kegiatan</h6>
	        </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
	              <div class="dataTable-container">
	              	<?php $this->widget('zii.widgets.grid.CGridView', array(
						'id'=>'kegiatan-grid',
						'dataProvider'=>$model->search(),
						'filter'=>$model,
						'summaryText'=>'<div class="summaryCustom">Showing {start} to {end} of {count} entries</div>',
						'itemsCssClass'=>'table table-flush dataTable-table',
						'columns'=>array(
							array(
								'header'=>'#',
								'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
								'htmlOptions'=>array('width'=>'10px','style'=>'text-align:center')
							),
							array(
								'name'=>'nama_kegiatan','type'=>'raw',
							  	'value'=>'CHtml::link(substr($data->nama_kegiatan,0,30)."...",array("kegiatan/view","id"=>$data->kg_id),array("class"=>"badge badge-sm bg-gradient-secondary"))',
								'htmlOptions'=>array('class'=>'text-sm font-weight-bold mb-0'),
			  				'headerHtmlOptions'=>array('class'=>'text-uppercase text-secondary text-xxs font-weight-bolder opacity-7')
							),
							array(
								'name'=>'tgl_kegiatan','type'=>'raw',
								'value'=>'$data->tgl_kegiatan',
								'htmlOptions'=>array('class'=>'text-sm font-weight-bold mb-0'),
			  				'headerHtmlOptions'=>array('class'=>'text-uppercase text-secondary text-xxs font-weight-bolder opacity-7')								
							),
							array(
								'name'=>'person_in_charge','type'=>'raw',
								'value'=>'$data->person_in_charge',
								'htmlOptions'=>array('class'=>'text-sm font-weight-bold mb-0'),
			  				'headerHtmlOptions'=>array('class'=>'text-uppercase text-secondary text-xxs font-weight-bolder opacity-7')								
							),
							array(
								'header'=>'Aksi',
								'class'=>'CButtonColumn',
								'template'=>'{update} {delete}',
								'htmlOptions'=>array('class'=>'text-sm font-weight-bold mb-0'),

			  				'headerHtmlOptions'=>array('class'=>'text-uppercase text-secondary text-xxs font-weight-bolder opacity-7')								
							),
						),
					)); ?>
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>

protected/views/kegiatan/create.php
<?php
    $this->pageTitle="Kegiatan";
    $this->breadcrumbs=array(
        'Kegiatan'=>array('admin'),
        'Create'
    );
?>

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
                <div class="pull-right">
                    <input type="button" value="Go Back" onclick="history.back(-1)" class='btn btn-default'/>
                </div>
                <h6>Create Kegiatan</h6>
            </div>
            <div class="card-body">
                <?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
            </div>
          </div>
        </div>
    </div>  
</div>  

protected/views/kegiatan/index.php
<?php
/* @var $this KegiatanController */
/* @var $dataProvider CActiveDataProvider */
date_default_timezone_set('Asia/Jakarta');

$Url = Yii::app()->baseUrl; 
$now = date('Y-m-d');
$kegiatanNow = Yii::app()->db->createCommand("SELECT nama_kegiatan FROM kegiatan WHERE tgl_kegiatan='$now' ORDER BY kg_id ASC LIMIT 1")->queryScalar();
$lokasi_kegiatan = Yii::app()->db->createCommand("SELECT lokasi_kegiatan FROM kegiatan WHERE tgl_kegiatan='$now' ORDER BY kg_id ASC LIMIT 1")->queryScalar();

$this->pageTitle="Kegiatan";
$this->breadcrumbs=array(
	'Kalendar Kegiatan'=>array('index')
);

?>
 <div class="container-fluid py-4">
      <div class="row">
        <div class="col-8">
          <div class="card mb-4">
            <div class="card-header pb-0 px-3">
	            <h6>Kalender Kegiatan</h6>
	        	</div>
            <div class="card-body px-3 pt-0 pb-2">
						<?php $this->widget('ext.fullcalendar.EFullCalendarHeart', array(
							//'themeCssFile'=>'cupertino/jquery-ui.min.css',
							'options'=>array(
								'header'=>array(
									'left'=>'prev,next,today',
									'center'=>'title',
									'right'=>'month,agendaWeek,agendaDay',
								),
								'events'=>$this->createUrl('kegiatan/calendarEvents'), // URL to get event
								'eventClick'=> 'js:function(calEvent, jsEvent, view) {
							        $("#myModalHeader").html(calEvent.title);
							        $("#myModalBody").load("'.Yii::app()->createUrl("kegiatan/view/id/").'/"+calEvent.id+"?asModal=true");
							        $("#myModal").modal();
							    }',
							)));
						?>
						</div>
					</div>
				</div>
        <div class="col-4">
          <div class="card mb-4">
            <div class="card-header pb-0 px-3">
							Today, <?php echo date('d F Y');?>
	        	</div>
            <div class="card-body px-3 pt-0 pb-2">
						<div class="add-calendar">
							<?php 
							if ($kegiatanNow != ''){
							echo "<b>".$kegiatanNow."</b>";?><br>
							<div style="display: flex;">
								<i class="fa fa-map-marker" style="font-size: 15px;margin-right: 10px"></i> 
								<div style="font-size: 12px;display: inline;">
									<?php echo $lokasi_kegiatan;?>
								</div>
							</div>
							<?php } else {?>
								<b>Tidak ada kegiatan hari ini</b>
							<?php }?>
						</div>
						<hr>
						<?php if (Yii::app()->user->record->level == 1){ ?>
						<a href="<?php echo $Url;?>/kegiatan/create">
							<div class="add-calendar">
								<div class="pull-right"><i class="fa fa-plus"></i></div>
								Add<br><br>
								<div style="display: flex;">
								<i class="fa fa-calendar" style="font-size: 30px;margin-right: 10px"></i> 
								<div style="font-size: 12px;display: inline;">Set up your calendars to see where<br>You need to be</div>
								</div>
							</div>
						</a>
						<hr class="horizontal dark mt-3">
						<a href="<?php echo $Url;?>/kegiatan/admin">
							<div class="add-calendar">
								<div class="pull-right"><i class="fa fa-cog"></i></div>
								Manage<br><br>
								<div style="display: flex;">
								<i class="fa fa-th" style="font-size: 30px;margin-right: 10px"></i> 
								<div style="font-size: 12px;display: inline;">Manage kegiatan</div>
								</div>
							</div>
						</a>
						<hr class="horizontal dark mt-3">
						<a href="<?php echo $Url;?>/kegiatan/excel">
							<div class="add-calendar">
								<div class="pull-right"><i class="fa fa-print"></i></div>
								Print<br><br>
								<div style="display: flex;">
								<i class="fa fa-file-excel-o" style="font-size: 30px;margin-right: 10px"></i> 
								<div style="font-size: 12px;display: inline;">Export Kalendar Kegiatan kedalam file excel</div>
								</div>
							</div>
						</a>
						<hr class="horizontal dark mt-3">
						<?php } else { } ?>
						</div>
					</div>
				</div>
			</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="myModalHeader" style="font-weight: 900">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p id="myModalBody"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

protected/views/kegiatan/update.php
<?php
    $this->pageTitle="Kegiatan";
    $this->breadcrumbs=array(
        'Kegiatan'=>array('admin'),
        'Update'
    );
?>

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
                <div class="pull-right">
                    <input type="button" value="Go Back" onclick="history.back(-1)" class='btn btn-default'/>
                </div>
                <h6>Update Kegiatan</h6>
            </div>
            <div class="card-body">
                <?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
            </div>
          </div>
        </div>
    </div>  
</div>  